name: Android library

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-android
      - run: ./gradlew --no-daemon :frontend:assembleDebug
